FROM node:22-alpine as build

WORKDIR /app

COPY ./package*.json .

RUN npm install

COPY . .

RUN npm run build
FROM node:22-alpine

WORKDIR /app

run npm install -g serve

COPY --from=build /app/dist ./dist

EXPOSE 3000

CMD [ "serve", "-s", "dist", "-l", "3000" ]


